# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SurveyPoint
                                 A QGIS plugin
 This plugin is helpful to create survey points and put them to database.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-12-27
        copyright            : (C) 2020 by Szymek Sleczka
        email                : szymonsleczka7@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SurveyPoint class from file SurveyPoint.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .SurveyPoint import SurveyPoint
    return SurveyPoint(iface)
