# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SurveyPointDialog
                                 A QGIS plugin
 This plugin is helpful to create survey points and put them to database.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-12-27
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Szymek Sleczka
        email                : szymonsleczka7@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.gui import QgsMapCanvas

from .engine import main
from SurveyPoint.ui.createPointsWindow import CreatePointsWindow
from SurveyPoint.ui.attributesWindow import AttributesWindow
from SurveyPoint.ui.databaseWindow import DatabaseWindow


#from .Second_window_test import Ui_Dialog - te usunac jak wyjdzie w main
#from .Second_win_test2 import SecondWindow

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'SurveyPoint_dialog_base.ui'))


class SurveyPointDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(SurveyPointDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        #create main instance
        self.create_pts = main.Create_points(QgsMapCanvas())
        self.attrs = main.Attributes()
        self.database = main.Database()

        #new window btns

        self.crt_win_btns = CreatePointsWindow()

        #self.crt_win_btns.pb_crt_pts.clicked.connect(self.create_points)
        #self.pb_create_pts_new_wind.clicked.connect(self.create_points_window)
        #self.pb_create_pts_new_wind.clicked.connect(self.create_points)

        self.pb_create_attrs_new_wind.clicked.connect(self.create_attributes_window)
        self.pb_create_db_new_wind.clicked.connect(self.create_database_window)

        

        
    def create_points(self):
        QgsMapCanvas().setMapTool(self.create_pts)
        #print('cos jest')
        #self.create_pts.create_pts()        
    
    def create_points_window(self):
        self.create_pts.create_points_window()

    def create_attributes_window(self):
        self.attrs.attributes_window()

    def create_database_window(self):
        self.database.database_window()


