# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SurveyPointDialog
                                 A QGIS plugin
 This plugin is helpful to create survey points and put them to database.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-12-27
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Szymek Sleczka
        email                : szymonsleczka7@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.utils import iface
from qgis.gui import QgsMapToolEmitPoint

from SurveyPoint.engine import main

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'createPointsWindow.ui'))


class CreatePointsWindow(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(CreatePointsWindow, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self.iface = iface
        
        self.create_pts = main.Create_points(self.iface.mapCanvas())
        self.pb_crt_pts.clicked.connect(self.my_edit_tool)

    def my_edit_tool(self):
        self.iface.mapCanvas().setMapTool(self.create_pts)



        
